### ISSUE TITLE
Failed to install fiber in macOS. 🤗 

### ISSUE THREAD

**Issue by CarlValenzuela96** [gofiber/cli#115]
**Question description**
I installed fiber using the instructions but it still won't let me use the fiber command, the console says it doesn't exist. I use macOS and Go version 1.18.

![Captura de Pantalla 2022-09-08 a la(s) 13 02 32](https://user-images.githubusercontent.com/13548264/189182712-3a5b203c-073a-4a2e-a735-9f8410f75c9b.png)

**Comment by hcancelik** [comment]
@CarlValenzuela96 Try installing with `go install github.com/gofiber/cli/fiber@latest` and make sure go bin is in your path.

`export PATH=$PATH:$HOME/go/bin`

**Comment by dsikes** [comment]
can we add  `go install github.com/gofiber/cli/fiber@latest` to the readme? 
I tried opening a PR but i get a 403 when trying to push. 

@ReneWerner87  any thoughts?

Thanks!

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/cli/commit/f105f0320dcf95237b36fd02b8659345fed8ca7e ok ?

**Comment by ReneWerner87** [comment]
closed with commit https://github.com/gofiber/cli/commit/f105f0320dcf95237b36fd02b8659345fed8ca7e
