### ISSUE TITLE
🐛 unable to install cli

### ISSUE THREAD

**Issue by dsikes** [gofiber/cli#32]
**Issue description**

When I attempt to run `go get -u github.com/gofiber/cli/fiber` a few errors are raised. Please see the screenshot below for the errors.

![image](https://user-images.githubusercontent.com/8764573/97738693-1b0a6180-1ab5-11eb-8cb6-195dfb20e0a0.png)

**Comment by kiyonlin** [comment]
@dsikes Thanks for reporting it! 

Already fixed. Please try again.

**Comment by dsikes** [comment]
Works now. Really like the CLI tool. Great work!
