### ISSUE TITLE
🚀 Dev command with custom commands before restart the application

### ISSUE THREAD

**Issue by hadihammurabi** [gofiber/cli#41]
**Is your feature request related to a problem?**
Yes, sometimes, we want to run some commands before restart the application again.

**Describe the solution you'd like**
Provide an option to put custom commands before restarting the application.
E. g. `fiber dev --before-restart "swag init"`

**Comment by kiyonlin** [comment]
Hey @hadihammurabi this is a good idea 👍 We'll support it soon.

**Comment by kiyonlin** [comment]
Please try `go get -u github.com/gofiber/cli/fiber` to update the cli 😄

**Comment by hadihammurabi** [comment]
Wowww realy love it, thankyou 😃
