### ISSUE TITLE
Pass arguments to go binary🚀 

### ISSUE THREAD

**Issue by jhwz** [gofiber/cli#53]
**Is your feature request related to a problem?**
No!

**Describe the solution you'd like**
Would like to run ```fiber dev``` on a CLI tool.

Could add ```-a, --args``` flag to specify the arguments to pass to exec.

I think it would be fairly simple to add, can create a pull request if need be.

**Comment by kiyonlin** [comment]
Sounds good. Feel free to make a pull request 😃
